### ISSUE TITLE
Please release the environment requirement to run the model 

### ISSUE THREAD

**Issue by QingCheng24** [jwh97nn/DeepDPS#5]
Hi, thank you for the impressive work!

I have a problem to start the training of this work.  I've checked Detectron2 is installed correctly as I can train the official examples. The MaskFormer op is built according to [this](https://github.com/fundamentalvision/Deformable-DETR). Could you please release the environment requirement along with the running instructions. It would be even better if you can give some advice on addessing the following issue. 

When running training with this model, I encountered an issue with the following error message

- cu11.7+torch1.31
```
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
...
ERROR [07/15 16:06:35 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  ...
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/maskformer.py", line 356, in forward
    losses = self.criterion(outputs, targets, depths)
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/criterion.py", line 555, in forward
    indices = self.matcher(outputs_without_aux, targets, depths)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/matcher.py", line 324, in forward
    return self.memory_efficient_forward(outputs, targets, depths)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/matcher.py", line 250, in memory_efficient_forward
    point_coords = torch.rand(1, self.num_points, 2, device=out_mask.device)
RuntimeError: CUDA error: device-side assert triggered
```

- cu12.1+torch2.31
```
/opt/conda/conda-bld/pytorch_1716905979055/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [90,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
...
ERROR [07/15 16:20:00 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/maskformer.py", line 356, in forward
    losses = self.criterion(outputs, targets, depths)
...
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/criterion.py", line 555, in forward
    indices = self.matcher(outputs_without_aux, targets, depths)
...
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/matcher.py", line 324, in forward
    return self.memory_efficient_forward(outputs, targets, depths)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/test/ws/panoptic/depth/image-based/DeepDPS/model/maskformer/matcher.py", line 201, in memory_efficient_forward
    cost_class = -out_prob[:, tgt_ids]
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by uowei** [comment]
@QingCheng24 
![image](https://github.com/user-attachments/assets/afa0cbf4-ee16-4063-8c65-fc784b9e1229)

Have you successfully trained this network? 

Although I was able to run it, the results are very poor. 

The segmentation performance is very bad, which leads to a poor overall DPQ score. 

As shown in the image, my segmentation score is 0, and no matter how much I adjust, I cannot resolve this issue. 

Have you encountered this problem as well?

**Comment by QingCheng24** [comment]
Hi @uowei, 

I'm able to run the code as well but the performance is similarly bad. I'm not able to reproduce the reported results with the given datasets. Although DeepDPS is based on Mask2Former, the panoptic results of DeepDPS can't outperform Mask2Former's.

**Comment by uowei** [comment]
Hi @QingCheng24,

Thank you for your prompt response. 
Is your segmentation performance also showing as 0 like mine? If not, could you kindly share how you modified it?

Currently, I suspect that the issue might be related to my setting for `SEM_SEG_HEAD: NUM_CLASSES` being set to 65, while the author set it to 19. 

However, when I change it to 19, I encounter the following error that I am unable to resolve:

```
`[01/03 16:49:50 d2.engine.train_loop]: Starting training from iteration 0
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [38,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [51,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [103,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [116,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [12,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [25,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [64,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [77,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [90,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [7,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [20,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [72,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [85,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [41,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [54,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [106,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [119,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [33,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [46,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [59,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [2,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [15,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [28,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [98,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [111,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [67,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [80,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1716905975447/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [93,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
ERROR [01/03 16:49:56 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/mnt/d/detectron2/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/mnt/d/detectron2/detectron2/engine/defaults.py", line 502, in run_step
    self._trainer.run_step()
  File "/mnt/d/detectron2/detectron2/engine/train_loop.py", line 310, in run_step
    loss_dict = self.model(data)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/maskformer.py", line 359, in forward
    losses = self.criterion(outputs, targets, depths)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/criterion.py", line 558, in forward
    indices = self.matcher(outputs_without_aux, targets, depths)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/matcher.py", line 342, in forward
    return self.memory_efficient_forward(outputs, targets, depths)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/matcher.py", line 212, in memory_efficient_forward
    cost_class = -out_prob[:, tgt_ids]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[01/03 16:49:56 d2.engine.hooks]: Total training time: 0:00:06 (0:00:00 on hooks)
[01/03 16:49:56 d2.utils.events]:  iter: 0       lr: N/A  max_mem: 4263M
Traceback (most recent call last):
  File "train_mask.py", line 384, in <module>
    launch(
  File "/mnt/d/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_mask.py", line 373, in main
    result = trainer.train()                  
  File "/mnt/d/detectron2/detectron2/engine/defaults.py", line 489, in train
    super().train(self.start_iter, self.max_iter)  
  File "/mnt/d/detectron2/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/mnt/d/detectron2/detectron2/engine/defaults.py", line 502, in run_step
    self._trainer.run_step()
  File "/mnt/d/detectron2/detectron2/engine/train_loop.py", line 310, in run_step
    loss_dict = self.model(data)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/maskformer.py", line 359, in forward
    losses = self.criterion(outputs, targets, depths)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/criterion.py", line 558, in forward
    indices = self.matcher(outputs_without_aux, targets, depths)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/matcher.py", line 342, in forward
    return self.memory_efficient_forward(outputs, targets, depths)
  File "/home/william/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/DeepDPS-main/model/maskformer/matcher.py", line 212, in memory_efficient_forward
    cost_class = -out_prob[:, tgt_ids]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`
```

Could you please advise how you resolved this issue?

Thank you!
